version: '3.0'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/${APP_NAME}
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    ports:
      - "8093:80"
    networks:
      tournaments_net:
        ipv4_address: 173.30.1.1
    depends_on:
      - php-fpm
      - db

  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        user: zloradnij
        uid: 1000
        workDir: ${APP_NAME}
    volumes:
      - ./:/${APP_NAME}
    container_name: ${PROJECT_NAME}-php
    networks:
      tournaments_net:
        ipv4_address: 173.30.1.2
    depends_on:
      - db

  db:
    container_name: ${APP_NAME}-db
    image: postgres:15
    restart: unless-stopped
    volumes:
      - tournaments-pg:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DATABASE=${DB_DATABASE}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '5438:5432'
    expose:
      - "5438"
    networks:
      tournaments_net:
        ipv4_address: 173.30.1.3

###> doctrine/doctrine-bundle ###
#  database:
#    image: postgres:${POSTGRES_VERSION:-15}-alpine
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-app}
#      # You should definitely change the password in production
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#      POSTGRES_USER: ${POSTGRES_USER:-app}
#    volumes:
#      - database_data:/var/lib/postgresql/data:rw
#      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

networks:
  tournaments_net:
    ipam:
      driver: default
      config:
        - subnet: 173.30.0.0/16

volumes:
  tournaments-pg:

###> doctrine/doctrine-bundle ###
#  database_data:
###< doctrine/doctrine-bundle ###
